name: "Bump package version"
description: "Bumping package version depending on keywords present in the commit message"

inputs:
  keywords:
    description: "Keywords to look for in last commit message"
    default: "[Major],[Minor],[Patch]"

runs:
  using: "node12"
  main: "dist/index.js"

branding:
  icon: git-commit
  color: gray-dark
